[book]
authors = ["GardenLinux"]
language = "en"
multilingual = false
src = "src"
title = "GardenLinux Next-Gen Build System"
description = "Architecture, user guide and implementation reference for gl-ng."

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = ""
edit-url-template = ""
no-section-label = false
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 2
